---
title: "P8105_hw4_xj2249_dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
data("ny_noaa")

cp_noaa <-
  ny_noaa %>% 
  filter(id == "USW00094728") %>% 
  separate(date, c("year", "month", "day"), sep = "-") %>% 
  mutate(
          id = recode(id, "USW00094728" = "CentralPark_NY"),
          prcp = prcp / 10,
          tmin = as.numeric(tmin) / 10,
          tmax = as.numeric(tmax) / 10,
          year = factor(year)
  )
```

Column {data-width=600}
-----------------------------------------------------------------------

###  Month-by-month average max temperatures 1981-2010
```{r}
cp_noaa %>% 
  group_by(year,month) %>% 
  summarise(mean_tmax = mean(tmax)) %>% 
  plot_ly(x = ~month, y = ~mean_tmax , color = ~year, 
          type = "scatter" , mode = "lines",
          alpha = 0.5
          ) %>% 
  layout(title = "Month-by-month average max temperatures 1981-2010")
```

Column {data-width=400}
-----------------------------------------------------------------------
### The annual average precipitation
```{r}
cp_noaa %>%
  group_by(year) %>% 
  summarise(precipitation = mean(prcp)) %>% 
  plot_ly(x = ~year, y = ~precipitation, color = ~year, type = "bar")

```


### The average min temperatures in Nov.  (Winter is coming!) 
```{r}
cp_noaa %>% 
        filter( month == 11) %>% 
        plot_ly(y = ~tmin , x = ~year, 
                type = "box" )
```


